% functional connectivity with SEM

% do BMS with LME generated by semopy_demo.py
% with data from get_betas_for_tetrad.m

%load('semopy_trial_onset_lmes.mat');
load('semopy_feedback_onset_lmes.mat');
%load('semopy_residuals_lmes.mat');

[alpha,exp_r,xp,pxp,bor,g] = bms(lme);

pxp
bor



